[package]
name = "voyager-2021/facdustory"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
private = true

[dependencies]
cmdr = "evaera/cmdr@1.12.0"

[server-dependencies]
